import test from 'node:test';
import assert from 'node:assert/strict';
import {coverageCheck,businessCheck,collectQuality} from '../runner/quality-adapters.mjs';
import {parseCoverage} from '../lib/integrations.mjs';
const artifacts={hash:'release',files:[{path:'classes/Request.cls',content:'public class Request {}'}]};
test('coverage parser does not convert missing counts to zero',()=>{const rows=parseCoverage('<m:codeCoverage><m:name>Request</m:name><m:numLocations>10</m:numLocations><m:numLocationsNotCovered>2</m:numLocationsNotCovered></m:codeCoverage><codeCoverage><name>Missing</name></codeCoverage>');assert.equal(rows[0].uncovered,2);assert.equal(rows[1].locations,null);assert.equal(coverageCheck(artifacts,{done:true,success:true,coverage:rows}).status,'passed');});
test('coverage blocks missing, ambiguous and impossible data; fails below threshold',()=>{for(const coverage of [[],[{name:'Request',locations:0,uncovered:0}],[{name:'Request',locations:10,uncovered:11}],[{name:'Request',locations:10,uncovered:0},{name:'Request',locations:10,uncovered:0}]])assert.equal(coverageCheck(artifacts,{done:true,success:true,coverage}).status,'blocked');assert.equal(coverageCheck(artifacts,{done:true,success:true,coverage:[{name:'Request',locations:100,uncovered:26}]}).status,'failed');});
test('business evidence refuses dropped, duplicate, failed or rewritten scenarios',()=>{const cases=[{id:'CASE-1',requirementId:'REQ-1',acceptanceIndex:0,expected:'Saved'}],suite={scenarios:[{id:'TEST-1',caseId:'CASE-1',requirements:['REQ-1'],expected:'Saved'}]};assert.equal(businessCheck(cases,suite,[{id:'TEST-1',passed:true}]).status,'passed');assert.equal(businessCheck(cases,suite,[]).status,'blocked');assert.equal(businessCheck(cases,suite,[{id:'TEST-1',passed:true},{id:'TEST-1',passed:true}]).status,'blocked');assert.equal(businessCheck(cases,suite,[{id:'TEST-1',passed:false}]).status,'failed');suite.scenarios[0].expected='Anything';assert.equal(businessCheck(cases,suite,[{id:'TEST-1',passed:true}]).status,'blocked');});
test('unimplemented categories stay blocked regardless of passing tests',()=>{const r=collectQuality({artifacts,validation:{},cases:[],testSuite:{scenarios:[]},tests:[]});assert.equal(r.checks.license.status,'blocked');assert.equal(r.checks.security.status,'blocked');assert.equal(r.checks.performance.status,'blocked');});
